-- AlterTable
ALTER TABLE "Branch" ADD COLUMN     "address" TEXT,
ADD COLUMN     "budget" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "currency" TEXT,
ADD COLUMN     "initialStaff" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "managerEmail" TEXT,
ADD COLUMN     "managerPhone" TEXT,
ADD COLUMN     "maxStaff" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "openingDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "revenueTarget" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "taxRegion" TEXT,
ADD COLUMN     "type" TEXT;
